INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (1, 'Ichilov Hospital', 'Tiberias, Street 106');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (2, 'Bnai Zion Hospital', 'Nazareth, Street 27');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (3, 'Ziv Hospital', 'Rehovot, Street 29');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (4, 'Wolfson Hospital', 'Rehovot, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (5, 'Meir Hospital', 'Tiberias, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (6, 'Bnai Zion Hospital', 'Haifa, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (7, 'Ziv Hospital', 'Netanya, Street 65');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (8, 'Poriya Hospital', 'Netanya, Street 149');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (9, 'Meir Hospital', 'Safed, Street 109');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (10, 'Bnai Zion Hospital', 'Haifa, Street 29');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (11, 'Barzilai Hospital', 'Safed, Street 121');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (12, 'Assuta Hospital', 'Netanya, Street 110');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (13, 'Rambam Hospital', 'Nazareth, Street 86');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (14, 'Bnai Zion Hospital', 'Holon, Street 38');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (15, 'HaEmek Hospital', 'Beer Sheva, Street 122');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (16, 'Rambam Hospital', 'Nazareth, Street 115');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (17, 'Sheba Hospital', 'Netanya, Street 28');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (18, 'Meir Hospital', 'Afula, Street 24');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (19, 'Laniado Hospital', 'Nazareth, Street 68');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (20, 'Meir Hospital', 'Afula, Street 87');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (21, 'Wolfson Hospital', 'Tel Aviv, Street 4');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (22, 'Ziv Hospital', 'Netanya, Street 19');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (23, 'HaEmek Hospital', 'Haifa, Street 77');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (24, 'Sheba Hospital', 'Haifa, Street 145');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (25, 'Ichilov Hospital', 'Afula, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (26, 'Meir Hospital', 'Ashkelon, Street 18');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (27, 'Bnai Zion Hospital', 'Safed, Street 36');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (28, 'Poriya Hospital', 'Tiberias, Street 118');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (29, 'Meir Hospital', 'Petah Tikva, Street 98');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (30, 'Ziv Hospital', 'Haifa, Street 145');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (31, 'Ziv Hospital', 'Netanya, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (32, 'Poriya Hospital', 'Jerusalem, Street 63');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (33, 'Rambam Hospital', 'Ashkelon, Street 95');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (34, 'Wolfson Hospital', 'Raanana, Street 52');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (35, 'Rambam Hospital', 'Tel Aviv, Street 31');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (36, 'Rambam Hospital', 'Haifa, Street 73');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (37, 'Soroka Hospital', 'Beer Sheva, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (38, 'Assuta Hospital', 'Beer Sheva, Street 141');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (39, 'Laniado Hospital', 'Rehovot, Street 50');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (40, 'Meir Hospital', 'Holon, Street 105');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (41, 'Meir Hospital', 'Safed, Street 137');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (42, 'Bnai Zion Hospital', 'Rehovot, Street 4');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (43, 'Poriya Hospital', 'Tiberias, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (44, 'Poriya Hospital', 'Beer Sheva, Street 72');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (45, 'Rambam Hospital', 'Ashkelon, Street 8');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (46, 'Meir Hospital', 'Nazareth, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (47, 'Meir Hospital', 'Afula, Street 116');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (48, 'Bnai Zion Hospital', 'Afula, Street 126');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (49, 'Wolfson Hospital', 'Beer Sheva, Street 101');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (50, 'Barzilai Hospital', 'Tel Aviv, Street 93');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (51, 'Rambam Hospital', 'Tel Aviv, Street 14');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (52, 'Ziv Hospital', 'Jerusalem, Street 142');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (53, 'Ichilov Hospital', 'Afula, Street 54');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (54, 'HaEmek Hospital', 'Ashkelon, Street 92');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (55, 'Sheba Hospital', 'Tiberias, Street 121');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (56, 'Rambam Hospital', 'Petah Tikva, Street 6');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (57, 'Meir Hospital', 'Jerusalem, Street 119');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (58, 'Assuta Hospital', 'Nazareth, Street 50');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (59, 'Assuta Hospital', 'Holon, Street 141');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (60, 'Barzilai Hospital', 'Netanya, Street 132');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (61, 'Hadassah Hospital', 'Afula, Street 88');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (62, 'HaEmek Hospital', 'Afula, Street 37');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (63, 'Sheba Hospital', 'Afula, Street 14');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (64, 'Rambam Hospital', 'Raanana, Street 132');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (65, 'Assuta Hospital', 'Tiberias, Street 49');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (66, 'Kaplan Hospital', 'Nazareth, Street 91');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (67, 'Wolfson Hospital', 'Safed, Street 147');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (68, 'Bnai Zion Hospital', 'Netanya, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (69, 'Ichilov Hospital', 'Tiberias, Street 120');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (70, 'Laniado Hospital', 'Beer Sheva, Street 77');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (71, 'Kaplan Hospital', 'Petah Tikva, Street 83');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (72, 'Sheba Hospital', 'Tel Aviv, Street 65');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (73, 'Poriya Hospital', 'Holon, Street 146');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (74, 'HaEmek Hospital', 'Beer Sheva, Street 109');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (75, 'Ziv Hospital', 'Netanya, Street 111');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (76, 'Ichilov Hospital', 'Petah Tikva, Street 58');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (77, 'Bnai Zion Hospital', 'Ashkelon, Street 32');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (78, 'Hadassah Hospital', 'Netanya, Street 27');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (79, 'Rambam Hospital', 'Holon, Street 125');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (80, 'Poriya Hospital', 'Holon, Street 16');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (81, 'Laniado Hospital', 'Tiberias, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (82, 'HaEmek Hospital', 'Raanana, Street 129');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (83, 'Laniado Hospital', 'Netanya, Street 82');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (84, 'Ichilov Hospital', 'Tiberias, Street 54');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (85, 'Assuta Hospital', 'Nazareth, Street 32');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (86, 'Sheba Hospital', 'Netanya, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (87, 'Barzilai Hospital', 'Jerusalem, Street 84');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (88, 'Kaplan Hospital', 'Afula, Street 132');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (89, 'HaEmek Hospital', 'Tiberias, Street 127');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (90, 'Kaplan Hospital', 'Haifa, Street 95');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (91, 'Rambam Hospital', 'Haifa, Street 67');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (92, 'Hadassah Hospital', 'Rehovot, Street 83');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (93, 'Sheba Hospital', 'Petah Tikva, Street 101');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (94, 'Rambam Hospital', 'Netanya, Street 84');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (95, 'Kaplan Hospital', 'Raanana, Street 110');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (96, 'Sheba Hospital', 'Netanya, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (97, 'Ziv Hospital', 'Ashkelon, Street 126');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (98, 'Hadassah Hospital', 'Beer Sheva, Street 104');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (99, 'Wolfson Hospital', 'Beer Sheva, Street 27');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (100, 'Hadassah Hospital', 'Beer Sheva, Street 122');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (101, 'HaEmek Hospital', 'Tiberias, Street 43');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (102, 'Poriya Hospital', 'Petah Tikva, Street 93');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (103, 'Wolfson Hospital', 'Safed, Street 26');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (104, 'Meir Hospital', 'Ashkelon, Street 83');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (105, 'Soroka Hospital', 'Rehovot, Street 148');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (106, 'Poriya Hospital', 'Haifa, Street 109');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (107, 'Soroka Hospital', 'Nazareth, Street 6');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (108, 'Soroka Hospital', 'Ashkelon, Street 73');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (109, 'HaEmek Hospital', 'Netanya, Street 89');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (110, 'Barzilai Hospital', 'Netanya, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (111, 'Sheba Hospital', 'Ashkelon, Street 76');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (112, 'Bnai Zion Hospital', 'Beer Sheva, Street 42');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (113, 'Sheba Hospital', 'Ashkelon, Street 95');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (114, 'HaEmek Hospital', 'Tel Aviv, Street 146');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (115, 'Bnai Zion Hospital', 'Nazareth, Street 8');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (116, 'Sheba Hospital', 'Beer Sheva, Street 42');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (117, 'HaEmek Hospital', 'Netanya, Street 73');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (118, 'Rambam Hospital', 'Afula, Street 99');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (119, 'Barzilai Hospital', 'Tiberias, Street 34');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (120, 'Soroka Hospital', 'Safed, Street 138');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (121, 'Ziv Hospital', 'Afula, Street 134');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (122, 'Bnai Zion Hospital', 'Ashkelon, Street 94');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (123, 'Barzilai Hospital', 'Haifa, Street 78');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (124, 'Barzilai Hospital', 'Petah Tikva, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (125, 'Assuta Hospital', 'Rehovot, Street 108');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (126, 'Meir Hospital', 'Raanana, Street 111');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (127, 'Poriya Hospital', 'Tiberias, Street 104');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (128, 'Laniado Hospital', 'Safed, Street 43');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (129, 'Laniado Hospital', 'Haifa, Street 123');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (130, 'Wolfson Hospital', 'Afula, Street 55');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (131, 'Rambam Hospital', 'Rehovot, Street 15');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (132, 'Assuta Hospital', 'Safed, Street 48');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (133, 'Sheba Hospital', 'Netanya, Street 42');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (134, 'Kaplan Hospital', 'Ashkelon, Street 127');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (135, 'Wolfson Hospital', 'Beer Sheva, Street 85');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (136, 'Poriya Hospital', 'Jerusalem, Street 123');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (137, 'Poriya Hospital', 'Tel Aviv, Street 104');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (138, 'Soroka Hospital', 'Petah Tikva, Street 146');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (139, 'Kaplan Hospital', 'Netanya, Street 62');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (140, 'Barzilai Hospital', 'Beer Sheva, Street 55');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (141, 'Sheba Hospital', 'Netanya, Street 91');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (142, 'Bnai Zion Hospital', 'Raanana, Street 91');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (143, 'Rambam Hospital', 'Holon, Street 99');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (144, 'Laniado Hospital', 'Tiberias, Street 108');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (145, 'Laniado Hospital', 'Beer Sheva, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (146, 'Barzilai Hospital', 'Tiberias, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (147, 'Ichilov Hospital', 'Safed, Street 18');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (148, 'Barzilai Hospital', 'Petah Tikva, Street 82');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (149, 'Hadassah Hospital', 'Afula, Street 13');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (150, 'Wolfson Hospital', 'Afula, Street 86');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (151, 'Wolfson Hospital', 'Haifa, Street 141');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (152, 'Kaplan Hospital', 'Afula, Street 135');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (153, 'Bnai Zion Hospital', 'Ashkelon, Street 117');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (154, 'HaEmek Hospital', 'Beer Sheva, Street 109');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (155, 'Rambam Hospital', 'Netanya, Street 127');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (156, 'Sheba Hospital', 'Afula, Street 143');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (157, 'Bnai Zion Hospital', 'Haifa, Street 74');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (158, 'Meir Hospital', 'Raanana, Street 95');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (159, 'Sheba Hospital', 'Ashkelon, Street 39');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (160, 'Assuta Hospital', 'Raanana, Street 125');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (161, 'Bnai Zion Hospital', 'Jerusalem, Street 137');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (162, 'Soroka Hospital', 'Tel Aviv, Street 127');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (163, 'HaEmek Hospital', 'Rehovot, Street 34');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (164, 'Sheba Hospital', 'Nazareth, Street 113');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (165, 'Rambam Hospital', 'Afula, Street 44');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (166, 'Soroka Hospital', 'Holon, Street 150');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (167, 'Sheba Hospital', 'Raanana, Street 99');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (168, 'Barzilai Hospital', 'Beer Sheva, Street 96');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (169, 'Bnai Zion Hospital', 'Petah Tikva, Street 5');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (170, 'Barzilai Hospital', 'Beer Sheva, Street 149');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (171, 'Poriya Hospital', 'Haifa, Street 109');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (172, 'Poriya Hospital', 'Nazareth, Street 93');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (173, 'Meir Hospital', 'Petah Tikva, Street 52');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (174, 'Barzilai Hospital', 'Haifa, Street 10');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (175, 'Meir Hospital', 'Beer Sheva, Street 124');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (176, 'Poriya Hospital', 'Jerusalem, Street 25');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (177, 'HaEmek Hospital', 'Safed, Street 23');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (178, 'Assuta Hospital', 'Tel Aviv, Street 67');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (179, 'Ziv Hospital', 'Rehovot, Street 35');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (180, 'Meir Hospital', 'Rehovot, Street 40');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (181, 'Ichilov Hospital', 'Nazareth, Street 58');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (182, 'Rambam Hospital', 'Jerusalem, Street 81');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (183, 'Rambam Hospital', 'Jerusalem, Street 68');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (184, 'Ziv Hospital', 'Nazareth, Street 120');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (185, 'Wolfson Hospital', 'Haifa, Street 121');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (186, 'Hadassah Hospital', 'Ashkelon, Street 87');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (187, 'Assuta Hospital', 'Ashkelon, Street 107');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (188, 'Soroka Hospital', 'Safed, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (189, 'Soroka Hospital', 'Haifa, Street 51');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (190, 'HaEmek Hospital', 'Holon, Street 18');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (191, 'Bnai Zion Hospital', 'Jerusalem, Street 142');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (192, 'Bnai Zion Hospital', 'Ashkelon, Street 123');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (193, 'Bnai Zion Hospital', 'Tel Aviv, Street 81');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (194, 'Rambam Hospital', 'Holon, Street 99');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (195, 'Wolfson Hospital', 'Haifa, Street 96');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (196, 'Laniado Hospital', 'Afula, Street 81');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (197, 'Sheba Hospital', 'Beer Sheva, Street 48');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (198, 'Bnai Zion Hospital', 'Beer Sheva, Street 54');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (199, 'Wolfson Hospital', 'Beer Sheva, Street 143');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (200, 'Ziv Hospital', 'Holon, Street 77');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (201, 'Rambam Hospital', 'Netanya, Street 72');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (202, 'Ichilov Hospital', 'Afula, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (203, 'Hadassah Hospital', 'Nazareth, Street 148');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (204, 'Laniado Hospital', 'Tiberias, Street 32');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (205, 'Barzilai Hospital', 'Netanya, Street 61');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (206, 'Wolfson Hospital', 'Raanana, Street 112');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (207, 'Hadassah Hospital', 'Jerusalem, Street 69');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (208, 'Rambam Hospital', 'Tel Aviv, Street 98');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (209, 'Ziv Hospital', 'Ashkelon, Street 84');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (210, 'Kaplan Hospital', 'Petah Tikva, Street 132');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (211, 'Wolfson Hospital', 'Holon, Street 14');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (212, 'Assuta Hospital', 'Tiberias, Street 100');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (213, 'Hadassah Hospital', 'Petah Tikva, Street 140');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (214, 'Barzilai Hospital', 'Ashkelon, Street 128');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (215, 'Wolfson Hospital', 'Netanya, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (216, 'Barzilai Hospital', 'Holon, Street 71');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (217, 'Poriya Hospital', 'Petah Tikva, Street 101');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (218, 'Hadassah Hospital', 'Tiberias, Street 45');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (219, 'Assuta Hospital', 'Netanya, Street 44');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (220, 'Barzilai Hospital', 'Ashkelon, Street 39');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (221, 'Soroka Hospital', 'Ashkelon, Street 96');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (222, 'Meir Hospital', 'Netanya, Street 71');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (223, 'Hadassah Hospital', 'Holon, Street 104');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (224, 'Bnai Zion Hospital', 'Safed, Street 60');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (225, 'Assuta Hospital', 'Raanana, Street 83');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (226, 'Ziv Hospital', 'Tiberias, Street 36');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (227, 'Hadassah Hospital', 'Nazareth, Street 109');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (228, 'Assuta Hospital', 'Haifa, Street 113');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (229, 'Wolfson Hospital', 'Holon, Street 146');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (230, 'Laniado Hospital', 'Beer Sheva, Street 52');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (231, 'Sheba Hospital', 'Jerusalem, Street 128');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (232, 'Wolfson Hospital', 'Beer Sheva, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (233, 'Ichilov Hospital', 'Beer Sheva, Street 148');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (234, 'Poriya Hospital', 'Safed, Street 136');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (235, 'Assuta Hospital', 'Netanya, Street 135');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (236, 'Hadassah Hospital', 'Beer Sheva, Street 40');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (237, 'Barzilai Hospital', 'Ashkelon, Street 57');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (238, 'Assuta Hospital', 'Tel Aviv, Street 111');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (239, 'HaEmek Hospital', 'Afula, Street 34');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (240, 'Sheba Hospital', 'Haifa, Street 52');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (241, 'Ziv Hospital', 'Safed, Street 27');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (242, 'Barzilai Hospital', 'Haifa, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (243, 'Hadassah Hospital', 'Ashkelon, Street 26');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (244, 'Meir Hospital', 'Afula, Street 130');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (245, 'Rambam Hospital', 'Ashkelon, Street 39');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (246, 'Laniado Hospital', 'Nazareth, Street 139');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (247, 'Assuta Hospital', 'Tiberias, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (248, 'Laniado Hospital', 'Beer Sheva, Street 134');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (249, 'Laniado Hospital', 'Haifa, Street 121');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (250, 'Laniado Hospital', 'Nazareth, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (251, 'Barzilai Hospital', 'Haifa, Street 10');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (252, 'Wolfson Hospital', 'Tiberias, Street 74');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (253, 'Wolfson Hospital', 'Netanya, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (254, 'Sheba Hospital', 'Tel Aviv, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (255, 'Kaplan Hospital', 'Afula, Street 126');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (256, 'Kaplan Hospital', 'Nazareth, Street 100');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (257, 'Laniado Hospital', 'Holon, Street 113');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (258, 'Ichilov Hospital', 'Beer Sheva, Street 87');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (259, 'Laniado Hospital', 'Ashkelon, Street 53');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (260, 'Hadassah Hospital', 'Tel Aviv, Street 103');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (261, 'Meir Hospital', 'Netanya, Street 35');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (262, 'Ichilov Hospital', 'Tel Aviv, Street 35');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (263, 'Ziv Hospital', 'Raanana, Street 86');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (264, 'Assuta Hospital', 'Nazareth, Street 53');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (265, 'HaEmek Hospital', 'Tiberias, Street 99');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (266, 'Barzilai Hospital', 'Ashkelon, Street 15');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (267, 'Hadassah Hospital', 'Raanana, Street 106');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (268, 'Kaplan Hospital', 'Holon, Street 118');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (269, 'Hadassah Hospital', 'Rehovot, Street 34');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (270, 'Hadassah Hospital', 'Rehovot, Street 2');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (271, 'Ziv Hospital', 'Raanana, Street 132');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (272, 'Sheba Hospital', 'Petah Tikva, Street 54');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (273, 'Ichilov Hospital', 'Jerusalem, Street 147');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (274, 'Hadassah Hospital', 'Jerusalem, Street 49');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (275, 'HaEmek Hospital', 'Beer Sheva, Street 79');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (276, 'Sheba Hospital', 'Tiberias, Street 141');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (277, 'Wolfson Hospital', 'Haifa, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (278, 'Laniado Hospital', 'Afula, Street 112');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (279, 'Laniado Hospital', 'Holon, Street 30');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (280, 'Laniado Hospital', 'Petah Tikva, Street 112');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (281, 'Bnai Zion Hospital', 'Holon, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (282, 'Bnai Zion Hospital', 'Petah Tikva, Street 56');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (283, 'Barzilai Hospital', 'Holon, Street 8');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (284, 'Ziv Hospital', 'Afula, Street 43');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (285, 'Ichilov Hospital', 'Tiberias, Street 130');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (286, 'Hadassah Hospital', 'Petah Tikva, Street 125');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (287, 'Assuta Hospital', 'Jerusalem, Street 69');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (288, 'Ichilov Hospital', 'Haifa, Street 128');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (289, 'Sheba Hospital', 'Netanya, Street 65');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (290, 'Kaplan Hospital', 'Jerusalem, Street 52');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (291, 'Assuta Hospital', 'Beer Sheva, Street 131');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (292, 'Ichilov Hospital', 'Raanana, Street 58');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (293, 'Poriya Hospital', 'Rehovot, Street 96');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (294, 'Sheba Hospital', 'Haifa, Street 45');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (295, 'Ichilov Hospital', 'Nazareth, Street 70');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (296, 'Assuta Hospital', 'Petah Tikva, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (297, 'Laniado Hospital', 'Raanana, Street 147');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (298, 'Poriya Hospital', 'Afula, Street 135');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (299, 'Poriya Hospital', 'Haifa, Street 103');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (300, 'HaEmek Hospital', 'Holon, Street 92');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (301, 'Rambam Hospital', 'Nazareth, Street 87');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (302, 'Soroka Hospital', 'Safed, Street 134');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (303, 'Rambam Hospital', 'Raanana, Street 70');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (304, 'Barzilai Hospital', 'Nazareth, Street 29');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (305, 'Soroka Hospital', 'Holon, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (306, 'Hadassah Hospital', 'Haifa, Street 91');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (307, 'Soroka Hospital', 'Netanya, Street 146');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (308, 'Ziv Hospital', 'Jerusalem, Street 45');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (309, 'Soroka Hospital', 'Tiberias, Street 65');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (310, 'HaEmek Hospital', 'Rehovot, Street 43');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (311, 'Meir Hospital', 'Jerusalem, Street 62');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (312, 'Assuta Hospital', 'Raanana, Street 53');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (313, 'Rambam Hospital', 'Rehovot, Street 65');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (314, 'Ichilov Hospital', 'Nazareth, Street 32');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (315, 'Rambam Hospital', 'Nazareth, Street 61');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (316, 'Barzilai Hospital', 'Tiberias, Street 21');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (317, 'Hadassah Hospital', 'Safed, Street 2');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (318, 'HaEmek Hospital', 'Beer Sheva, Street 101');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (319, 'Sheba Hospital', 'Jerusalem, Street 119');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (320, 'Soroka Hospital', 'Safed, Street 51');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (321, 'Hadassah Hospital', 'Tiberias, Street 8');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (322, 'Laniado Hospital', 'Safed, Street 63');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (323, 'Laniado Hospital', 'Nazareth, Street 71');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (324, 'Soroka Hospital', 'Nazareth, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (325, 'Assuta Hospital', 'Netanya, Street 4');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (326, 'Laniado Hospital', 'Holon, Street 40');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (327, 'Wolfson Hospital', 'Safed, Street 15');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (328, 'Hadassah Hospital', 'Raanana, Street 86');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (329, 'Poriya Hospital', 'Beer Sheva, Street 98');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (330, 'Wolfson Hospital', 'Nazareth, Street 30');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (331, 'Bnai Zion Hospital', 'Petah Tikva, Street 41');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (332, 'Meir Hospital', 'Netanya, Street 76');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (333, 'HaEmek Hospital', 'Rehovot, Street 11');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (334, 'HaEmek Hospital', 'Ashkelon, Street 107');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (335, 'Ichilov Hospital', 'Netanya, Street 144');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (336, 'Bnai Zion Hospital', 'Jerusalem, Street 32');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (337, 'Barzilai Hospital', 'Safed, Street 14');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (338, 'HaEmek Hospital', 'Tel Aviv, Street 143');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (339, 'Poriya Hospital', 'Beer Sheva, Street 28');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (340, 'Sheba Hospital', 'Jerusalem, Street 103');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (341, 'Laniado Hospital', 'Beer Sheva, Street 27');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (342, 'Meir Hospital', 'Petah Tikva, Street 127');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (343, 'Kaplan Hospital', 'Petah Tikva, Street 140');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (344, 'Kaplan Hospital', 'Ashkelon, Street 104');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (345, 'Laniado Hospital', 'Raanana, Street 142');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (346, 'Sheba Hospital', 'Rehovot, Street 130');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (347, 'Bnai Zion Hospital', 'Haifa, Street 92');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (348, 'Barzilai Hospital', 'Raanana, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (349, 'Ziv Hospital', 'Tiberias, Street 36');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (350, 'Assuta Hospital', 'Nazareth, Street 57');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (351, 'Ichilov Hospital', 'Raanana, Street 114');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (352, 'Hadassah Hospital', 'Beer Sheva, Street 133');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (353, 'Meir Hospital', 'Safed, Street 106');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (354, 'Ziv Hospital', 'Holon, Street 3');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (355, 'Meir Hospital', 'Safed, Street 108');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (356, 'Barzilai Hospital', 'Tel Aviv, Street 78');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (357, 'Laniado Hospital', 'Jerusalem, Street 67');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (358, 'Bnai Zion Hospital', 'Ashkelon, Street 98');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (359, 'Meir Hospital', 'Ashkelon, Street 120');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (360, 'Wolfson Hospital', 'Tel Aviv, Street 135');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (361, 'Assuta Hospital', 'Tel Aviv, Street 75');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (362, 'Rambam Hospital', 'Haifa, Street 104');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (363, 'Kaplan Hospital', 'Raanana, Street 8');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (364, 'Bnai Zion Hospital', 'Beer Sheva, Street 37');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (365, 'Hadassah Hospital', 'Jerusalem, Street 4');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (366, 'Soroka Hospital', 'Afula, Street 38');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (367, 'Poriya Hospital', 'Afula, Street 90');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (368, 'Meir Hospital', 'Afula, Street 59');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (369, 'Hadassah Hospital', 'Beer Sheva, Street 134');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (370, 'Assuta Hospital', 'Ashkelon, Street 56');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (371, 'Barzilai Hospital', 'Rehovot, Street 116');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (372, 'Laniado Hospital', 'Ashkelon, Street 133');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (373, 'Sheba Hospital', 'Netanya, Street 5');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (374, 'Kaplan Hospital', 'Beer Sheva, Street 128');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (375, 'HaEmek Hospital', 'Tiberias, Street 101');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (376, 'HaEmek Hospital', 'Rehovot, Street 97');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (377, 'Poriya Hospital', 'Holon, Street 61');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (378, 'Wolfson Hospital', 'Tiberias, Street 139');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (379, 'Ziv Hospital', 'Rehovot, Street 148');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (380, 'Ichilov Hospital', 'Nazareth, Street 47');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (381, 'Kaplan Hospital', 'Petah Tikva, Street 17');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (382, 'Kaplan Hospital', 'Jerusalem, Street 92');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (383, 'Assuta Hospital', 'Safed, Street 47');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (384, 'Laniado Hospital', 'Rehovot, Street 58');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (385, 'Ichilov Hospital', 'Tiberias, Street 71');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (386, 'Soroka Hospital', 'Haifa, Street 56');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (387, 'Kaplan Hospital', 'Safed, Street 22');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (388, 'Bnai Zion Hospital', 'Beer Sheva, Street 138');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (389, 'Soroka Hospital', 'Safed, Street 142');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (390, 'Poriya Hospital', 'Petah Tikva, Street 122');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (391, 'Rambam Hospital', 'Ashkelon, Street 78');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (392, 'Ichilov Hospital', 'Rehovot, Street 92');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (393, 'Wolfson Hospital', 'Jerusalem, Street 96');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (394, 'Assuta Hospital', 'Jerusalem, Street 26');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (395, 'Ichilov Hospital', 'Afula, Street 9');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (396, 'Meir Hospital', 'Safed, Street 84');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (397, 'Rambam Hospital', 'Netanya, Street 81');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (398, 'Hadassah Hospital', 'Ashkelon, Street 107');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (399, 'Sheba Hospital', 'Ashkelon, Street 107');
INSERT INTO Hospital (hospital_id, hospital_name, address) VALUES (400, 'Ziv Hospital', 'Afula, Street 80');
