INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (1, 'Tel Aviv', 12, '2023-02-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (2, 'Haifa', 25, '2023-06-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (3, 'Rehovot', 26, '2023-10-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (4, 'Tel Aviv', 50, '2023-08-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (5, 'Afula', 21, '2023-03-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (6, 'Petah Tikva', 13, '2023-01-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (7, 'Afula', 11, '2023-04-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (8, 'Jerusalem', 28, '2023-07-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (9, 'Afula', 20, '2023-04-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (10, 'Netanya', 33, '2023-04-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (11, 'Afula', 31, '2023-07-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (12, 'Netanya', 9, '2023-06-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (13, 'Tel Aviv', 46, '2023-06-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (14, 'Beer Sheva', 46, '2023-04-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (15, 'Haifa', 19, '2023-02-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (16, 'Petah Tikva', 40, '2023-09-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (17, 'Holon', 9, '2023-10-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (18, 'Ashkelon', 2, '2023-09-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (19, 'Petah Tikva', 41, '2023-05-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (20, 'Beer Sheva', 19, '2023-05-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (21, 'Jerusalem', 16, '2023-04-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (22, 'Rehovot', 2, '2023-05-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (23, 'Rehovot', 28, '2023-05-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (24, 'Tel Aviv', 17, '2023-01-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (25, 'Ashkelon', 27, '2023-10-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (26, 'Beer Sheva', 42, '2023-06-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (27, 'Holon', 21, '2023-07-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (28, 'Petah Tikva', 30, '2023-05-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (29, 'Rehovot', 6, '2023-10-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (30, 'Ashkelon', 44, '2023-11-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (31, 'Afula', 33, '2023-08-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (32, 'Netanya', 32, '2023-10-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (33, 'Tel Aviv', 9, '2023-12-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (34, 'Jerusalem', 45, '2023-11-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (35, 'Beer Sheva', 22, '2023-12-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (36, 'Haifa', 4, '2023-01-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (37, 'Jerusalem', 24, '2023-06-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (38, 'Rehovot', 22, '2023-12-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (39, 'Petah Tikva', 50, '2023-06-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (40, 'Beer Sheva', 46, '2023-01-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (41, 'Tel Aviv', 28, '2023-05-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (42, 'Holon', 23, '2023-06-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (43, 'Afula', 36, '2023-11-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (44, 'Haifa', 38, '2023-11-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (45, 'Rehovot', 40, '2023-02-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (46, 'Beer Sheva', 48, '2023-10-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (47, 'Holon', 22, '2023-10-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (48, 'Haifa', 35, '2023-05-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (49, 'Holon', 35, '2023-04-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (50, 'Haifa', 16, '2023-07-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (51, 'Ashkelon', 11, '2023-09-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (52, 'Haifa', 19, '2023-01-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (53, 'Beer Sheva', 8, '2023-08-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (54, 'Ashkelon', 16, '2023-12-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (55, 'Netanya', 20, '2023-12-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (56, 'Jerusalem', 43, '2023-03-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (57, 'Beer Sheva', 49, '2023-03-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (58, 'Ashkelon', 25, '2023-01-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (59, 'Jerusalem', 26, '2023-09-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (60, 'Tel Aviv', 35, '2023-01-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (61, 'Tel Aviv', 30, '2023-01-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (62, 'Tel Aviv', 5, '2023-12-08');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (63, 'Tel Aviv', 37, '2023-11-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (64, 'Afula', 32, '2023-06-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (65, 'Rehovot', 13, '2023-03-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (66, 'Haifa', 31, '2023-03-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (67, 'Ashkelon', 10, '2023-03-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (68, 'Haifa', 43, '2023-09-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (69, 'Beer Sheva', 47, '2023-03-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (70, 'Beer Sheva', 6, '2023-06-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (71, 'Beer Sheva', 47, '2023-01-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (72, 'Petah Tikva', 21, '2023-01-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (73, 'Petah Tikva', 45, '2023-04-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (74, 'Petah Tikva', 21, '2023-04-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (75, 'Rehovot', 32, '2023-09-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (76, 'Petah Tikva', 37, '2023-05-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (77, 'Afula', 20, '2023-11-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (78, 'Petah Tikva', 23, '2023-02-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (79, 'Haifa', 10, '2023-08-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (80, 'Rehovot', 17, '2023-06-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (81, 'Tel Aviv', 20, '2023-11-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (82, 'Beer Sheva', 8, '2023-04-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (83, 'Petah Tikva', 32, '2023-06-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (84, 'Netanya', 47, '2023-06-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (85, 'Rehovot', 14, '2023-04-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (86, 'Ashkelon', 49, '2023-07-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (87, 'Afula', 6, '2023-10-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (88, 'Netanya', 38, '2023-09-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (89, 'Holon', 12, '2023-07-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (90, 'Tel Aviv', 27, '2023-06-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (91, 'Jerusalem', 5, '2023-07-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (92, 'Tel Aviv', 5, '2023-04-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (93, 'Haifa', 18, '2023-08-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (94, 'Ashkelon', 10, '2023-04-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (95, 'Afula', 21, '2023-12-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (96, 'Ashkelon', 11, '2023-12-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (97, 'Jerusalem', 48, '2023-10-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (98, 'Tel Aviv', 14, '2023-09-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (99, 'Ashkelon', 5, '2023-06-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (100, 'Petah Tikva', 30, '2023-12-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (101, 'Haifa', 31, '2023-02-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (102, 'Rehovot', 45, '2023-07-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (103, 'Afula', 38, '2023-02-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (104, 'Afula', 2, '2023-02-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (105, 'Petah Tikva', 11, '2023-09-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (106, 'Rehovot', 22, '2023-08-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (107, 'Beer Sheva', 28, '2023-04-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (108, 'Tel Aviv', 33, '2023-01-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (109, 'Beer Sheva', 9, '2023-02-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (110, 'Ashkelon', 50, '2023-12-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (111, 'Jerusalem', 4, '2023-08-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (112, 'Rehovot', 46, '2023-06-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (113, 'Afula', 25, '2023-08-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (114, 'Rehovot', 42, '2023-11-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (115, 'Tel Aviv', 40, '2023-04-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (116, 'Afula', 8, '2023-12-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (117, 'Tel Aviv', 43, '2023-04-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (118, 'Petah Tikva', 49, '2023-01-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (119, 'Netanya', 25, '2023-08-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (120, 'Tel Aviv', 35, '2023-11-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (121, 'Rehovot', 26, '2023-07-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (122, 'Beer Sheva', 48, '2023-09-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (123, 'Netanya', 35, '2023-05-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (124, 'Holon', 29, '2023-04-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (125, 'Afula', 42, '2023-08-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (126, 'Petah Tikva', 42, '2023-06-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (127, 'Haifa', 36, '2023-12-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (128, 'Ashkelon', 19, '2023-04-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (129, 'Rehovot', 30, '2023-06-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (130, 'Petah Tikva', 1, '2023-07-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (131, 'Jerusalem', 32, '2023-08-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (132, 'Beer Sheva', 18, '2023-12-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (133, 'Haifa', 43, '2023-02-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (134, 'Beer Sheva', 27, '2023-01-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (135, 'Beer Sheva', 3, '2023-04-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (136, 'Netanya', 38, '2023-12-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (137, 'Tel Aviv', 15, '2023-09-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (138, 'Petah Tikva', 37, '2023-07-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (139, 'Afula', 35, '2023-08-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (140, 'Haifa', 7, '2023-04-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (141, 'Afula', 12, '2023-07-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (142, 'Tel Aviv', 28, '2023-12-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (143, 'Holon', 17, '2023-09-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (144, 'Tel Aviv', 28, '2023-05-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (145, 'Petah Tikva', 27, '2023-04-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (146, 'Tel Aviv', 12, '2023-10-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (147, 'Afula', 40, '2023-06-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (148, 'Holon', 5, '2023-12-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (149, 'Beer Sheva', 9, '2023-04-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (150, 'Rehovot', 29, '2023-03-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (151, 'Tel Aviv', 27, '2023-05-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (152, 'Haifa', 44, '2023-05-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (153, 'Petah Tikva', 31, '2023-12-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (154, 'Netanya', 31, '2023-10-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (155, 'Holon', 5, '2023-06-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (156, 'Holon', 24, '2023-07-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (157, 'Jerusalem', 3, '2023-11-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (158, 'Jerusalem', 16, '2023-03-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (159, 'Beer Sheva', 24, '2023-07-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (160, 'Haifa', 46, '2023-04-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (161, 'Beer Sheva', 35, '2023-05-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (162, 'Holon', 27, '2023-07-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (163, 'Holon', 3, '2023-09-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (164, 'Rehovot', 15, '2023-01-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (165, 'Rehovot', 37, '2023-12-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (166, 'Beer Sheva', 5, '2023-11-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (167, 'Ashkelon', 6, '2023-07-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (168, 'Tel Aviv', 1, '2023-03-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (169, 'Beer Sheva', 37, '2023-07-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (170, 'Haifa', 49, '2023-04-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (171, 'Jerusalem', 14, '2023-04-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (172, 'Ashkelon', 7, '2023-03-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (173, 'Rehovot', 31, '2023-08-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (174, 'Tel Aviv', 3, '2023-04-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (175, 'Rehovot', 10, '2023-11-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (176, 'Afula', 44, '2023-04-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (177, 'Jerusalem', 37, '2023-07-31');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (178, 'Afula', 48, '2023-04-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (179, 'Tel Aviv', 34, '2023-08-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (180, 'Petah Tikva', 3, '2023-12-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (181, 'Tel Aviv', 25, '2023-03-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (182, 'Netanya', 38, '2023-11-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (183, 'Ashkelon', 19, '2023-08-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (184, 'Ashkelon', 13, '2023-08-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (185, 'Ashkelon', 30, '2023-04-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (186, 'Netanya', 35, '2023-09-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (187, 'Netanya', 16, '2023-06-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (188, 'Beer Sheva', 41, '2023-01-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (189, 'Petah Tikva', 34, '2023-10-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (190, 'Ashkelon', 36, '2023-01-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (191, 'Petah Tikva', 12, '2023-09-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (192, 'Beer Sheva', 47, '2023-10-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (193, 'Holon', 28, '2023-02-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (194, 'Petah Tikva', 20, '2023-12-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (195, 'Afula', 18, '2023-11-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (196, 'Holon', 37, '2023-11-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (197, 'Petah Tikva', 9, '2023-12-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (198, 'Beer Sheva', 27, '2023-11-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (199, 'Haifa', 19, '2023-03-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (200, 'Rehovot', 14, '2023-03-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (201, 'Tel Aviv', 31, '2023-04-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (202, 'Afula', 28, '2023-11-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (203, 'Holon', 1, '2023-07-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (204, 'Haifa', 46, '2023-01-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (205, 'Holon', 28, '2023-04-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (206, 'Ashkelon', 33, '2023-03-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (207, 'Tel Aviv', 35, '2023-06-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (208, 'Tel Aviv', 42, '2023-08-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (209, 'Rehovot', 27, '2023-03-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (210, 'Holon', 18, '2023-06-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (211, 'Ashkelon', 23, '2023-01-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (212, 'Ashkelon', 15, '2023-10-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (213, 'Netanya', 3, '2023-02-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (214, 'Rehovot', 17, '2023-12-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (215, 'Rehovot', 1, '2023-08-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (216, 'Beer Sheva', 39, '2023-09-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (217, 'Haifa', 35, '2023-02-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (218, 'Ashkelon', 19, '2023-08-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (219, 'Ashkelon', 23, '2023-07-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (220, 'Beer Sheva', 32, '2023-01-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (221, 'Petah Tikva', 24, '2023-08-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (222, 'Jerusalem', 7, '2023-03-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (223, 'Rehovot', 24, '2023-04-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (224, 'Holon', 38, '2023-03-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (225, 'Jerusalem', 44, '2023-04-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (226, 'Ashkelon', 49, '2023-12-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (227, 'Tel Aviv', 42, '2023-09-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (228, 'Afula', 30, '2023-04-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (229, 'Petah Tikva', 50, '2023-11-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (230, 'Ashkelon', 38, '2023-02-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (231, 'Petah Tikva', 18, '2023-12-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (232, 'Ashkelon', 12, '2023-04-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (233, 'Petah Tikva', 24, '2023-12-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (234, 'Holon', 42, '2023-05-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (235, 'Netanya', 12, '2023-04-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (236, 'Afula', 40, '2023-02-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (237, 'Ashkelon', 18, '2023-09-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (238, 'Rehovot', 21, '2023-02-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (239, 'Afula', 10, '2023-03-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (240, 'Holon', 11, '2023-10-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (241, 'Afula', 48, '2023-10-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (242, 'Tel Aviv', 6, '2023-09-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (243, 'Afula', 22, '2023-12-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (244, 'Holon', 32, '2023-10-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (245, 'Tel Aviv', 46, '2023-08-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (246, 'Haifa', 5, '2023-03-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (247, 'Rehovot', 7, '2023-05-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (248, 'Beer Sheva', 29, '2023-04-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (249, 'Jerusalem', 44, '2023-06-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (250, 'Holon', 5, '2023-06-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (251, 'Ashkelon', 10, '2023-06-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (252, 'Rehovot', 20, '2023-05-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (253, 'Petah Tikva', 23, '2023-08-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (254, 'Ashkelon', 12, '2023-12-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (255, 'Holon', 33, '2023-04-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (256, 'Rehovot', 18, '2023-07-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (257, 'Afula', 24, '2023-12-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (258, 'Haifa', 45, '2023-08-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (259, 'Petah Tikva', 35, '2023-08-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (260, 'Jerusalem', 27, '2023-04-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (261, 'Jerusalem', 25, '2023-01-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (262, 'Haifa', 45, '2023-03-31');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (263, 'Petah Tikva', 35, '2023-05-31');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (264, 'Ashkelon', 22, '2023-03-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (265, 'Petah Tikva', 46, '2023-03-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (266, 'Beer Sheva', 4, '2023-08-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (267, 'Haifa', 12, '2023-12-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (268, 'Petah Tikva', 24, '2023-02-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (269, 'Holon', 46, '2023-06-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (270, 'Petah Tikva', 19, '2023-01-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (271, 'Haifa', 19, '2023-07-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (272, 'Ashkelon', 21, '2023-05-10');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (273, 'Holon', 23, '2023-07-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (274, 'Petah Tikva', 49, '2023-11-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (275, 'Ashkelon', 47, '2023-03-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (276, 'Netanya', 31, '2023-11-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (277, 'Netanya', 22, '2023-12-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (278, 'Netanya', 27, '2023-04-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (279, 'Haifa', 8, '2023-01-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (280, 'Haifa', 41, '2023-10-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (281, 'Petah Tikva', 42, '2023-03-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (282, 'Tel Aviv', 21, '2023-09-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (283, 'Netanya', 47, '2023-09-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (284, 'Haifa', 13, '2023-04-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (285, 'Haifa', 28, '2023-07-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (286, 'Tel Aviv', 32, '2023-10-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (287, 'Ashkelon', 10, '2023-07-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (288, 'Holon', 14, '2023-08-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (289, 'Petah Tikva', 46, '2023-05-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (290, 'Holon', 14, '2023-09-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (291, 'Rehovot', 32, '2023-04-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (292, 'Afula', 15, '2023-07-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (293, 'Afula', 39, '2023-02-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (294, 'Rehovot', 36, '2023-03-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (295, 'Beer Sheva', 15, '2023-05-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (296, 'Petah Tikva', 50, '2023-12-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (297, 'Afula', 9, '2023-07-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (298, 'Petah Tikva', 12, '2023-10-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (299, 'Afula', 46, '2023-11-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (300, 'Netanya', 23, '2023-10-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (301, 'Tel Aviv', 12, '2023-09-04');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (302, 'Beer Sheva', 43, '2023-10-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (303, 'Ashkelon', 28, '2023-03-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (304, 'Beer Sheva', 1, '2023-10-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (305, 'Petah Tikva', 25, '2023-03-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (306, 'Tel Aviv', 47, '2023-10-08');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (307, 'Tel Aviv', 18, '2023-10-08');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (308, 'Afula', 14, '2023-03-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (309, 'Netanya', 1, '2023-06-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (310, 'Afula', 50, '2023-03-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (311, 'Haifa', 17, '2023-02-09');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (312, 'Tel Aviv', 29, '2023-06-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (313, 'Haifa', 41, '2023-09-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (314, 'Petah Tikva', 30, '2023-09-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (315, 'Ashkelon', 43, '2023-08-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (316, 'Petah Tikva', 34, '2023-09-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (317, 'Beer Sheva', 28, '2023-05-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (318, 'Tel Aviv', 31, '2023-02-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (319, 'Haifa', 36, '2023-02-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (320, 'Petah Tikva', 17, '2023-09-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (321, 'Petah Tikva', 22, '2023-01-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (322, 'Netanya', 21, '2023-11-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (323, 'Jerusalem', 40, '2023-05-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (324, 'Afula', 46, '2023-09-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (325, 'Beer Sheva', 31, '2023-05-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (326, 'Ashkelon', 32, '2023-03-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (327, 'Petah Tikva', 26, '2023-07-12');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (328, 'Petah Tikva', 21, '2023-11-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (329, 'Jerusalem', 26, '2023-03-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (330, 'Tel Aviv', 36, '2023-08-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (331, 'Tel Aviv', 5, '2023-05-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (332, 'Holon', 13, '2023-03-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (333, 'Haifa', 5, '2023-10-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (334, 'Holon', 1, '2023-01-02');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (335, 'Rehovot', 48, '2023-05-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (336, 'Netanya', 44, '2023-08-31');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (337, 'Petah Tikva', 8, '2023-06-05');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (338, 'Holon', 44, '2023-06-03');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (339, 'Netanya', 36, '2023-01-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (340, 'Tel Aviv', 27, '2023-03-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (341, 'Haifa', 4, '2023-10-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (342, 'Haifa', 39, '2023-12-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (343, 'Netanya', 17, '2023-10-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (344, 'Holon', 37, '2023-12-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (345, 'Jerusalem', 50, '2023-12-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (346, 'Jerusalem', 5, '2023-05-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (347, 'Holon', 7, '2023-09-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (348, 'Netanya', 7, '2023-09-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (349, 'Tel Aviv', 28, '2023-03-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (350, 'Jerusalem', 44, '2023-10-31');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (351, 'Petah Tikva', 45, '2023-11-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (352, 'Jerusalem', 41, '2023-10-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (353, 'Tel Aviv', 43, '2023-03-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (354, 'Haifa', 35, '2023-11-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (355, 'Petah Tikva', 4, '2023-03-19');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (356, 'Holon', 23, '2023-10-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (357, 'Petah Tikva', 21, '2023-11-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (358, 'Haifa', 1, '2023-07-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (359, 'Ashkelon', 17, '2023-05-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (360, 'Afula', 17, '2023-09-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (361, 'Rehovot', 6, '2023-08-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (362, 'Holon', 18, '2023-08-15');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (363, 'Netanya', 42, '2023-04-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (364, 'Tel Aviv', 4, '2023-11-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (365, 'Ashkelon', 40, '2023-02-25');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (366, 'Ashkelon', 31, '2023-12-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (367, 'Rehovot', 44, '2023-11-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (368, 'Holon', 6, '2023-10-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (369, 'Haifa', 31, '2023-03-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (370, 'Rehovot', 11, '2023-05-08');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (371, 'Ashkelon', 10, '2023-12-11');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (372, 'Tel Aviv', 20, '2023-03-31');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (373, 'Petah Tikva', 37, '2023-12-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (374, 'Jerusalem', 31, '2023-12-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (375, 'Afula', 30, '2023-02-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (376, 'Haifa', 47, '2023-10-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (377, 'Ashkelon', 11, '2023-07-13');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (378, 'Rehovot', 35, '2023-12-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (379, 'Haifa', 44, '2023-11-23');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (380, 'Beer Sheva', 18, '2023-08-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (381, 'Beer Sheva', 11, '2023-02-26');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (382, 'Ashkelon', 3, '2023-08-20');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (383, 'Petah Tikva', 28, '2023-10-24');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (384, 'Holon', 4, '2023-08-16');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (385, 'Netanya', 39, '2023-04-07');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (386, 'Petah Tikva', 7, '2023-05-17');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (387, 'Tel Aviv', 18, '2023-09-21');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (388, 'Haifa', 13, '2023-06-06');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (389, 'Jerusalem', 17, '2023-01-14');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (390, 'Beer Sheva', 18, '2023-06-22');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (391, 'Afula', 1, '2023-12-30');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (392, 'Holon', 20, '2023-05-18');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (393, 'Beer Sheva', 32, '2023-11-01');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (394, 'Rehovot', 35, '2023-09-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (395, 'Petah Tikva', 29, '2023-11-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (396, 'Afula', 28, '2023-01-27');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (397, 'Tel Aviv', 7, '2023-07-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (398, 'Beer Sheva', 33, '2023-08-29');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (399, 'Netanya', 24, '2023-06-28');
INSERT INTO Medical_event (event_id, event_location, number_of_injured, event_date) VALUES (400, 'Tel Aviv', 16, '2023-08-14');
